### ISSUE TITLE
PATH_SECRET should be configurable

### ISSUE THREAD

**Issue by alexdparis** [stklcode/jvaultconnector#45]
The code doesn't work if one removes default "secret" engine for another one named differently.
Indeed, PATH_SECRET shouldn't be added for this kind of custom cases.

I suggest to either remove it and let the responsability to add it by the API client, or permit to configure it.

![image](https://user-images.githubusercontent.com/9102853/113184549-984d2480-9255-11eb-8f64-57030731dd79.png)

Example : With the following tree, the connector can't work, as it systematically adds a "secret/" prefix to the path.

![image](https://user-images.githubusercontent.com/9102853/113184596-ac912180-9255-11eb-9f7a-59d5a994cb5b.png)

**Comment by stklcode** [comment]
You can always replace the ` *Secret()` methods by the raw variants and add whichever mount point you like.
| secret method call             | equivalen call                           |
| ------------------------------- | --------------------------------------- |
| `readSecret("key")`            | `read("secret/key")`                     |
| `writeSecretData("key", data)` | `writeSecretData("secret", "key", data)` |
| `readSecretVersion("key", 1) ` | `readSecretVersion("secret", "key", 1)`  |
| `readSecretMetadata("key")`    | `readSecretMetadata("secret", "key")`    |

... and so on ...

I'd suggest to either deprecate the ` *Secret()` methods and remove them with 1.0 or replace them by something more generic like `defaultMount` (configurable) for convenience.

**Comment by alexdparis** [comment]
That's a good point, thanks ! I took the example from the readme which uses `readSecret`, I didn't think about the raw method. Thank you.

**Comment by stklcode** [comment]
I'm glad I could help.

Should probably clean up the docs and remove some legacy code some time. quite many convenience methods (secret, sql, ...) but there are so many possible Vault configurations (now) we cannot cover all anyway. Thanks for the reminder.
